# Generated by Django 3.0.7 on 2020-06-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.TextField()),
                ('owner', models.TextField()),
                ('expiry', models.TextField()),
                ('renew', models.TextField()),
            ],
        ),
    ]
