# Generated by Django 3.0.7 on 2020-06-14 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20200613_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
