# Generated by Django 3.0.7 on 2020-06-14 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_auto_20200613_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='link',
            new_name='domain_Link',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='domain_Name',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='owner',
            new_name='domain_Owner',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='renew',
            new_name='domain_Renew_Fee',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='expiry',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_Expiration',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
