# Generated by Django 3.0.7 on 2020-06-14 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_auto_20200613_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_Renew_TimePeriod',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
