# Generated by Django 3.0.7 on 2020-06-14 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_Registrar_Link',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
